services:
  - type: web
    name: projeto-nuvem-palavras
    runtime: node
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production 